# Compat shim: re-export env symbols from the new location
from .conf.env import (
    OPENAI_KEY, OPENAI_MODEL,
    SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY,
    AI_ENABLED, ENABLE_AI_TRAINING, ENABLE_PAPER_TRADING, ENABLE_TELEGRAM,
    BACKEND_URL, TICKLET_DATA_DIR, TICKLET_MODELS_DIR, TICKLET_LOGS_DIR
)